INSERT INTO API_SERVICES.SERVICES (ID, NAME, DESC, URL) VALUES
('SVC001', 'Biblioteca Digital', 'Acceso a recursos digitales y bibliografía en línea.', 'http://www.exampleuniversity.edu/library'),
('SVC002', 'Campus Virtual', 'Plataforma de educación en línea para estudiantes y profesores.', 'http://www.exampleuniversity.edu/campus'),
('SVC003', 'Servicio de Tutoría', 'Asistencia académica individualizada para estudiantes.', 'http://www.exampleuniversity.edu/tutoring'),
('SVC004', 'Portal de Noticias', 'Actualizaciones y noticias de la universidad.', 'http://www.exampleuniversity.edu/news'),
('SVC005', 'Servicio de Carreras', 'Recursos para la búsqueda de empleo y desarrollo profesional.', 'http://www.exampleuniversity.edu/career'),
('SVC006', 'Laboratorios Virtuales', 'Simulaciones y experimentos en línea para estudiantes.', 'http://www.exampleuniversity.edu/labs'),
('SVC007', 'Sistema de Gestión de Calificaciones', 'Visualización de calificaciones y evaluaciones.', 'http://www.exampleuniversity.edu/grades'),
('SVC008', 'Oficina de Registros', 'Gestión de matrículas, registros académicos y transcripciones.', 'http://www.exampleuniversity.edu/records'),
('SVC009', 'Centro de Recursos para Estudiantes', 'Acceso a materiales de estudio y recursos de apoyo.', 'http://www.exampleuniversity.edu/studentresources'),
('SVC010', 'Cafetería Universitaria', 'Lugar para comer y socializar en el campus.', 'http://www.exampleuniversity.edu/cafeteria'),
('SVC011', 'Deportes y Recreación', 'Instalaciones deportivas y actividades recreativas.', 'http://www.exampleuniversity.edu/sports'),
('SVC012', 'Consejería Estudiantil', 'Apoyo emocional y consejería para estudiantes.', 'http://www.exampleuniversity.edu/counseling'),
('SVC013', 'Club de Debate', 'Participación en debates y oratoria.', 'http://www.exampleuniversity.edu/debateclub'),
('SVC014', 'Asociación de Estudiantes', 'Participación en actividades estudiantiles y eventos.', 'http://www.exampleuniversity.edu/studentassociation'),
('SVC015', 'Servicio de Transporte', 'Transporte en el campus y rutas de autobús.', 'http://www.exampleuniversity.edu/transportation'),
('SVC016', 'Laboratorios de Investigación', 'Espacios para investigaciones académicas.', 'http://www.exampleuniversity.edu/researchlabs'),
('SVC017', 'Sala de Conferencias', 'Espacio para conferencias y eventos académicos.', 'http://www.exampleuniversity.edu/conferencehall'),
('SVC018', 'Programa de Intercambio', 'Oportunidades de intercambio estudiantil internacional.', 'http://www.exampleuniversity.edu/exchangeprogram'),
('SVC019', 'Servicio de Salud Estudiantil', 'Atención médica y servicios de salud para estudiantes.', 'http://www.exampleuniversity.edu/studenthealth'),
('SVC020', 'Programa de Voluntariado', 'Participación en actividades de voluntariado comunitario.', 'http://www.exampleuniversity.edu/volunteerprogram'),
('SVC021', 'Cine Universitario', 'Proyecciones de películas y eventos relacionados con el cine.', 'http://www.exampleuniversity.edu/universitycinema'),
('SVC022', 'Programa de Becas', 'Información y solicitud de becas para estudiantes.', 'http://www.exampleuniversity.edu/scholarshipprogram'),
('SVC023', 'Club de Fotografía', 'Participación en actividades relacionadas con la fotografía.', 'http://www.exampleuniversity.edu/photographyclub'),
('SVC024', 'Centro de Desarrollo Profesional', 'Asesoramiento y recursos para el desarrollo profesional.', 'http://www.exampleuniversity.edu/professionaldevelopment'),
('SVC025', 'Grupo de Teatro Universitario', 'Participación en producciones teatrales.', 'http://www.exampleuniversity.edu/theatreclub'),
('SVC026', 'Servicio de Consejería de Carrera', 'Asesoramiento de carrera y planificación profesional.', 'http://www.exampleuniversity.edu/careercounseling'),
('SVC027', 'Revista Estudiantil', 'Publicación y contribución a una revista estudiantil.', 'http://www.exampleuniversity.edu/studentmagazine'),
('SVC028', 'Estudio de Grabación', 'Grabación de música y proyectos de audio.', 'http://www.exampleuniversity.edu/recordingstudio'),
('SVC029', 'Servicio de Almuerzos', 'Opciones de comida en el campus para el almuerzo.', 'http://www.exampleuniversity.edu/lunchservice'),
('SVC030', 'Club de Ajedrez', 'Participación en partidas de ajedrez y torneos.', 'http://www.exampleuniversity.edu/chessclub'),
('SVC031', 'Centro de Innovación', 'Apoyo a la innovación y el espíritu empresarial.', 'http://www.exampleuniversity.edu/innovationcenter'),
('SVC032', 'Asociación de Padres y Familias', 'Participación y apoyo de los padres y familias de estudiantes.', 'http://www.exampleuniversity.edu/parentsassociation'),
('SVC033', 'Banda Universitaria', 'Participación en una banda musical universitaria.', 'http://www.exampleuniversity.edu/universityband'),
('SVC034', 'Club de Senderismo', 'Excursiones y actividades de senderismo al aire libre.', 'http://www.exampleuniversity.edu/hikingclub'),
('SVC035', 'Programa de Mentoría', 'Mentoría para estudiantes a cargo de alumnos mayores.', 'http://www.exampleuniversity.edu/mentoringprogram'),
('SVC036', 'Servicio de Reciclaje', 'Programa de reciclaje en el campus.', 'http://www.exampleuniversity.edu/recyclingservice'),
('SVC037', 'Casa de Estudiantes Internacionales', 'Apoyo y alojamiento para estudiantes internacionales.', 'http://www.exampleuniversity.edu/internationalhouse'),
('SVC038', 'Servicio de Orientación Vocacional', 'Ayuda en la elección de carrera y orientación vocacional.', 'http://www.exampleuniversity.edu/careeradvising');
