CREATE SCHEMA IF NOT EXISTS API_SERVICES;
DROP TABLE IF EXISTS API_SERVICES.SERVICES;

CREATE TABLE API_SERVICES.SERVICES (
  ID VARCHAR(25) PRIMARY KEY NOT NULL,
  NAME VARCHAR(250) NOT NULL,
  DESC VARCHAR(4000) NOT NULL,
  URL VARCHAR(512) NOT NULL
);
